class DocumentModel {
  final int id, bab, kelas_id;
  final String judul, deskripsi, file;

  DocumentModel({
    required this.id,
    required this.judul,
    required this.deskripsi,
    required this.bab,
    required this.kelas_id,
    required this.file
  });
}

List<DocumentModel> documentmodel = [
  DocumentModel(
		id: 16,
		judul:'Dokumen pertama',
		deskripsi:'Memancing lele',
		file:'1634808214.pdf',
		bab: 3,
		kelas_id: 4,
  ),
  DocumentModel(
		id: 17,
		judul: 'Dokumen kedua',
		deskripsi: 'dokumen kedua',
		file: '1634808275.pdf',
		bab: 1,
		kelas_id: 2,
  ),
  DocumentModel(
		id: 18,
		judul: 'Artikel 1',
		deskripsi: 'Memancing lele',
		file: '1634808351.pdf',
		bab: 1,
		kelas_id: 3,
  ),
  DocumentModel(
		id: 19,
		judul: 'Dokumen upin ipin',
		deskripsi: 'Memancing lele',
		file: '1634813956.pdf',
		bab: 1,
    kelas_id: 1,
  ),
  DocumentModel(
		id: 20,
		judul:'Dokumen pertama',
		deskripsi:'Memancing lele',
		file:'1634808214.pdf',
		bab: 3,
		kelas_id: 4,
  ),
  DocumentModel(
		id: 21,
		judul: 'Dokumen kedua',
		deskripsi: 'dokumen kedua',
		file: '1634808275.pdf',
		bab: 1,
		kelas_id: 2,
  ),
  DocumentModel(
		id: 22,
		judul: 'Artikel 1',
		deskripsi: 'Memancing lele',
		file: '1634808351.pdf',
		bab: 1,
		kelas_id: 3,
  ),
  DocumentModel(
		id: 23,
		judul: 'Dokumen upin ipin',
		deskripsi: 'Memancing lele',
		file: '1634813956.pdf',
		bab: 1,
    kelas_id: 1,
  ),
  DocumentModel(
		id: 24,
		judul:'Dokumen pertama',
		deskripsi:'Memancing lele',
		file:'1634808214.pdf',
		bab: 3,
		kelas_id: 4,
  ),
  DocumentModel(
		id: 25,
		judul: 'Dokumen kedua',
		deskripsi: 'dokumen kedua',
		file: '1634808275.pdf',
		bab: 1,
		kelas_id: 2,
  ),
  DocumentModel(
		id: 26,
		judul: 'Artikel 1',
		deskripsi: 'Memancing lele',
		file: '1634808351.pdf',
		bab: 1,
		kelas_id: 3,
  ),
  DocumentModel(
		id: 27,
		judul: 'Dokumen upin ipin',
		deskripsi: 'Memancing lele',
		file: '1634813956.pdf',
		bab: 1,
    kelas_id: 1,
  ),
  DocumentModel(
		id: 28,
		judul: 'Dokumen kedua',
		deskripsi: 'dokumen kedua',
		file: '1634808275.pdf',
		bab: 1,
		kelas_id: 2,
  ),
  DocumentModel(
		id: 29,
		judul: 'Artikel 1',
		deskripsi: 'Memancing lele',
		file: '1634808351.pdf',
		bab: 1,
		kelas_id: 3,
  ),
  DocumentModel(
		id: 30,
		judul: 'Dokumen upin ipin',
		deskripsi: 'Memancing lele',
		file: '1634813956.pdf',
		bab: 1,
    kelas_id: 1,
  ),
  DocumentModel(
		id: 31,
		judul:'Dokumen pertama',
		deskripsi:'Memancing lele',
		file:'1634808214.pdf',
		bab: 3,
		kelas_id: 4,
  ),
  DocumentModel(
		id: 32,
		judul: 'Dokumen kedua',
		deskripsi: 'dokumen kedua',
		file: '1634808275.pdf',
		bab: 1,
		kelas_id: 2,
  ),
  DocumentModel(
		id: 33,
		judul: 'Artikel 1',
		deskripsi: 'Memancing lele',
		file: '1634808351.pdf',
		bab: 1,
		kelas_id: 3,
  ),
  DocumentModel(
		id: 34,
		judul: 'Dokumen upin ipin',
		deskripsi: 'Memancing lele',
		file: '1634813956.pdf',
		bab: 1,
    kelas_id: 1,
  ),
];